### ISSUE TITLE
Not able to add custom Variables in request body

### ISSUE THREAD

**Issue by PritiDawdaIntellect** [apollographql/GitHunt-Angular#78]
How to introduce  custom variables in request body similar to default "Variables"  in Angular 2.
Below is expected request body format:
{
   "query":"",
   "variables":"{}",
   "customVariable1":"{}", //This is additional variable
   "customVariable2":"{}", //This is additional variable
   "operationName":""
}

**Comment by Darkbladecr** [comment]
GraphQL variables are all stored in the [variables key](http://dev.apollodata.com/core/apollo-client-api.html#ApolloClient\.watchQuery). If you want to send something extra with the request then I suggest you set headers instead. This can be done with the [networkInterface middlewares](http://dev.apollodata.com/core/network.html#networkInterfaceMiddleware).

**Comment by tomermoshe** [comment]
Like @Darkbladecr said, if you want to add default variables in addition to those passed in `variables` key you should add them as headers with the networkinterface middleware.
see: http://dev.apollodata.com/core/network.html#networkInterfaceMiddleware
